sudo: required

language: go
go:
    - 1.6
    - tip

services:
    - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty

before_install:
    - apt-cache madison docker-engine
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

script:
    - docker version
    - go get
    - go build
    - ./hmake all
    - ./bin/hmake-*-linux-amd64 check test e2e site -sv
