sudo: required

language: go
go:
    - 1.9
    - tip

services:
    - docker

script:
    - docker version
    - go get
    - go get -v github.com/golang/dep/cmd/dep
    - dep ensure
    - go build -o hmake ./
    - ./hmake all
    - ./bin/linux/amd64/hmake check test e2e site
