sudo: required

language: go
go:
    - 1.7
    - tip

services:
    - docker

env:
    global:
        - DOCKER_VERSION=1.12.1-0~trusty

before_install:
    - apt-cache madison docker-engine
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-engine=${DOCKER_VERSION}

script:
    - docker version
    - go get
    - go build
    - ./hmake all
    - ./bin/linux/amd64/hmake check test e2e site -sv
